# Generated by Django 5.2.7 on 2025-11-17 05:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('is_published', models.BooleanField(default=True, verbose_name='Published')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Published Date')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
