# Generated by Django 5.2.7 on 2025-11-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(default='images/defult.jpg', upload_to='images/'),
        ),
    ]
